### PR TITLE
Updated to latest JDA Version

### LINKED ISSUE #1: Update to stable release of JDA
Update to use a stable release of JDA, found in the releases section of the JDA github

### PR DESCRIPTION
**Pull request by byRoadrunner**
Updated the code to the latest JDA Version.
Fixes #1

### CODE REVIEW

**Comment by drewdorris** [comment]
Nice work, why'd you include a json dependency in there, though? I can't see any uses for it

**Comment by byRoadrunner** [comment]
It wasn't provided anymore by the latest version of JDA, so I had to include it separately.

**Comment by byRoadrunner** [comment]
I've just noticed I forgot to specify the scope (compile) for the json and JDA dependency. Please do not merge this. I will fix it as soon as I'm at home.

**Comment by byRoadrunner** [comment]
@dextonanderson u should add the compile scope in the pom.xml to JDA, otherwise it won´t work

**Comment by ds58** [comment]
> 
> 
> @dextonanderson u should add the compile scope in the pom.xml to JDA, otherwise it won´t work

It would have worked. Maven shade plugin would have added it by default. I did add it though, sorry it got lost in the commit because of all the tab->spaces conversion.

https://github.com/Ruinscraft/BotBoi/blob/master/BotBoi-Server/pom.xml#L33

**Comment by ds58** [comment]
> 
> 
> Nice work, why'd you include a json dependency in there, though? I can't see any uses for it

org.json was required because I/we (for some reason) used it instead of Gson for WebPurify responses. Apparently it used to be included in JDA.

**Pull request merged**
